databases:
  - name: RentACar
    databaseName: RentACar
    user: RentACar_3suc_user

services:
  - type: web
    name: RentACar
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: RentACar
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false